### ISSUE TITLE
How to Import .ply File into Unity and Enable User Navigation in the Scene

### ISSUE THREAD

**Issue by tsai-b10809052** [jonathanventura/3d-pano-inpainting#7]
After completing the step "7.Re-scale the mesh according to the known height of the camera off of the ground", I have generated a .ply file. I would like to import this file into Unity so that users can freely navigate within the scene. Could you provide guidance on the best approach to:

1. Import the .ply file into Unity
2. Set up the scene to allow user movement within the mesh environment

Any suggestions or resources would be greatly appreciated. Thank you!

**Comment by jonathanventura** [comment]
Hello, I believe Unity supports GLB files -- you should be able to change the suffix of the filename to `.glb` when running `estimate_scale_histogram.py` to get a GLB file:

    python mesh/estimate_scale_histogram.py input.ply output.glb

**Comment by tsai-b10809052** [comment]
Thank YOU!!!!!
